version: '3.8'

services:
  Auth-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "8080:80"
      - "8081:8081"
    environment:
      - Jwt:Key=6392f084ac5423fc2d833b164cba70c48cb24330
    depends_on:
      - Auth-db

volumes:
  mssql-data: